### ISSUE TITLE
histogram.py needs to be updated to python2

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/gxadmin#128]
histogram.py is used by gxadmin a bit and is python2 only atm.

@sanjaysrikakulam ported it to python3 here https://gist.github.com/sanjaysrikakulam/ba5b7ea35c34e1ee6c325d57de8eb717

I guess it would be nice to ship this newer version that works with latest Galaxy's

**Comment by hexylena** [comment]
Thanks for filing, closed in https://github.com/galaxyproject/gxadmin/commit/3ce12f712f612391242012ad76a34b3cc1f757f9
