### ISSUE TITLE
Report needs to support ##?

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/gxadmin#133]
```
galaxy@sn06:~$ gxadmin report data-info 110124855
ERROR:  syntax error at or near "OR"
LINE 18: AND (d.id= OR hda.id=)) to STDOUT with CSV DELIMITER E'\t'
```

**Comment by bgruening** [comment]
It seems the `##?` is not passing the `arg_` through. Those or not defined and empty in the function.

**Comment by hexylena** [comment]
`##?` isn't currently supported for `report_` type functions, I'll look into adding that.

**Comment by bgruening** [comment]
Oh, I'm eager to see that PR. I looked at the magic and suspected this, but couldn't find how to `import` or activate that magic.
