### ISSUE TITLE
InfluxDB V2 support 

### ISSUE THREAD

**Issue by NilsKrattinger** [galaxyproject/gxadmin#161]
Hi, 

I was wondering, as InfluxDB OSS V1 is no more under active maintenance, is there any plan to support InfluxDB OSS V2 on the meta influx part ?

**Comment by bgruening** [comment]
Speaking for EU, I think we will skip InfluxDB v2. They introduced a new query language that will cause a lot of work for us and afaik this query language is already deprecated and will be replaced in v3, which will use the same language as v1. Its a bit confusing I hope I got this right. We are waiting for v3.

**Comment by NilsKrattinger** [comment]
Yeah that makes sense, thanks for sharing.

For what I know yes, flux will be dropped and influxQL will be revived, along other ways to query.
